title: Shane Starcher
description: Random Software Developer
texture:
  title: Shane Starcher
  tagline: Resume
  date_format: "%b %-d, %Y"
  style: black

  social_links:
    untappd: sstarcher
    github:  sstarcher
    facebook: shanestarcher
    linkedIn: in/sstarcher # format: in/username or username
    discord: sstarcher
  analytics_id: 'UA-1959564-1'

# Build settings
theme: texture
remote_theme: samarsault/texture

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - devbox.json
  - devbox.lock
  - .devbox/
  - vendor/

page_gen:
  - data: recipes
    template: recipe
    name: name
    dir: recipes
    extension: html
